/******************************************************
 * This is the main file for the mips1 ArchC model    *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 
// Rodolfo editou aqui
//
#define CORE_NUM 1 

const char *project_name="mips1";
const char *project_file="mips1.ac";
const char *archc_version="2.0beta1";
const char *archc_options="-abi -dy ";

#include  <systemc.h>
#include  "mips1.H"
#include  "ac_tlm_mem.h"
#include  "roteador.h"
#include  "lock.h"
#include  "fatorial.h"
#include  <sstream>

using user::ac_tlm_mem;
using user::roteador;
using user::lock;
using user::factorial;

char** alloc_args(int n, char **av){
  char **av_cpy;
  int i;

  av_cpy = (char**)malloc(sizeof(char*)*n);
  for (i = 0; i < n; i++)
  {
    av_cpy[i]= (char*)malloc(sizeof(char)*strlen(av[i])+1);
  }
  
  return av_cpy;
}

void cpy_strings(int n, char **dest, char **origem){
  int i;
  for (i = 0; i < n; i++){
    strcpy(dest[i], origem[i]);
  }
}

int sc_main(int ac, char *av[])
{
  char **av2;

  //!  ISA simulator
  mips1 mips1_proc1("mips1_1");
  mips1 mips1_proc2("mips1_2");
  mips1 mips1_proc3("mips1_3");
  mips1 mips1_proc4("mips1_4");
  mips1 mips1_proc5("mips1_5");
  mips1 mips1_proc6("mips1_6");
  mips1 mips1_proc7("mips1_7");
  mips1 mips1_proc8("mips1_8");
  roteador rot("roteador", CORE_NUM);
  ac_tlm_mem mem("mem");
  lock lock1("lock_mem");
  factorial fatorial("fatorial");

#ifdef AC_DEBUG
  ac_trace("mips1_proc1.trace");
  ac_trace("mips1_proc2.trace");
  ac_trace("mips1_proc3.trace");
  ac_trace("mips1_proc4.trace");
  ac_trace("mips1_proc5.trace");
  ac_trace("mips1_proc6.trace");
  ac_trace("mips1_proc7.trace");
  ac_trace("mips1_proc8.trace");
#endif 
  
  //cria conexao entre roteador(master) e memoria(slave)
  rot.DM_port(mem.target_export);
  rot.LOCK_port(lock1.target_export);
  rot.F_port(fatorial.target_export);

  av2 = alloc_args(ac, av);
  
  //cria conexao entre processadores(master) e roteador(slave)
  mips1_proc1.DM_port(rot.target_export);
  mips1_proc2.DM_port(rot.target_export);
  mips1_proc3.DM_port(rot.target_export);  
  mips1_proc4.DM_port(rot.target_export);  
  mips1_proc5.DM_port(rot.target_export);  
  mips1_proc6.DM_port(rot.target_export);  
  mips1_proc7.DM_port(rot.target_export);  
  mips1_proc8.DM_port(rot.target_export);  

  cpy_strings(ac, av2, av);
  mips1_proc1.init(ac, av2);
  cpy_strings(ac, av2, av);
  mips1_proc2.init(ac, av2);
  cpy_strings(ac, av2, av);
  mips1_proc3.init(ac, av2);
  cpy_strings(ac, av2, av);
  mips1_proc4.init(ac, av2);
  cpy_strings(ac, av2, av);
  mips1_proc5.init(ac, av2);
  cpy_strings(ac, av2, av);
  mips1_proc6.init(ac, av2);
  cpy_strings(ac, av2, av);
  mips1_proc7.init(ac, av2);
  cpy_strings(ac, av2, av);
  mips1_proc8.init(ac, av2);
  

  cerr << endl;

  sc_start();

  mips1_proc1.PrintStat();
//   mips1_proc2.PrintStat();
//   mips1_proc3.PrintStat();
//   mips1_proc4.PrintStat();
//   mips1_proc5.PrintStat();
//   mips1_proc6.PrintStat();
//   mips1_proc7.PrintStat();
//   mips1_proc8.PrintStat();
  
  cerr << endl;

#ifdef AC_STATS
  mips1_proc1.ac_sim_stats.time = sc_simulation_time();
  mips1_proc1.ac_sim_stats.print();
  
  mips1_proc2.ac_sim_stats.time = sc_simulation_time();
  mips1_proc2.ac_sim_stats.print();
  
#endif 

#ifdef AC_DEBUG
  ac_close_trace();
#endif 

  return mips1_proc1.ac_exit_status || mips1_proc2.ac_exit_status;
}
